/*
 * Meetings Api
 *
 * Online meetings between doctors and patients management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: leoentiev.oliver@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

 package meetings

import (
   "net/http"

   "github.com/gin-gonic/gin"
)

type MeetingsListAPI interface {

   // internal registration of api routes
   addRoutes(routerGroup *gin.RouterGroup)

    // CreateMeeting - Creates new meeting
   CreateMeeting(ctx *gin.Context)

    // DeleteMeeting - Deletes specific meeting
   DeleteMeeting(ctx *gin.Context)

    // GetMeeting - Provides details about meeting
   GetMeeting(ctx *gin.Context)

    // GetMeetingsList - Provides the online meetings list
   GetMeetingsList(ctx *gin.Context)

    // UpdateMeeting - Updates specific meeting
   UpdateMeeting(ctx *gin.Context)

 }

// partial implementation of MeetingsListAPI - all functions must be implemented in add on files
type implMeetingsListAPI struct {

}

func newMeetingsListAPI() MeetingsListAPI {
	return &implMeetingsListAPI{}
}

func (this *implMeetingsListAPI) addRoutes(routerGroup *gin.RouterGroup) {
	routerGroup.Handle( http.MethodPost, "/meetings", this.CreateMeeting)
	routerGroup.Handle( http.MethodDelete, "/meetings/:entryId", this.DeleteMeeting)
	routerGroup.Handle( http.MethodGet, "/meetings/:entryId", this.GetMeeting)
	routerGroup.Handle( http.MethodGet, "/meetings", this.GetMeetingsList)
	routerGroup.Handle( http.MethodPut, "/meetings/:entryId", this.UpdateMeeting)
}

// Copy following section to separate file, uncomment, and implement accordingly
// // CreateMeeting - Creates new meeting
// func (this *implMeetingsListAPI) CreateMeeting(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteMeeting - Deletes specific meeting
// func (this *implMeetingsListAPI) DeleteMeeting(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetMeeting - Provides details about meeting
// func (this *implMeetingsListAPI) GetMeeting(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // GetMeetingsList - Provides the online meetings list
// func (this *implMeetingsListAPI) GetMeetingsList(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // UpdateMeeting - Updates specific meeting
// func (this *implMeetingsListAPI) UpdateMeeting(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//

