/*
 * Meetings Api
 *
 * Online meetings between doctors and patients management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: leoentiev.oliver@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package meetings

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newMeetingsListAPI()
    api.addRoutes(group)
  }
  
}